import fsPromises from 'fs/promises';
import path from 'path';

export async function setupReadme(projectPath: string, workspaceName: string) {
  const readmePath = path.join(projectPath, 'README.md');

  const readmeContent = [
    `# Morax `,
    '',
    'Welcome to your next-generation, high-performance monorepo workspace generated by **Morax**.',
    '',
    '## Workspace Structure',
    '',
    '- **`apps/`** — Frontend applications, backend servers, and user-facing services.',
    '- **`packages/`** — Shared modules, TypeScript configurations, ESLint rule sets, and common utility libraries.',
    '',
    '## Key Commands',
    '',
    'Run the following commands from the root directory of your workspace:',
    '',
    '### Development',
    'Start all dev servers and hot-reloading configurations concurrently:',
    '```bash',
    'pnpm dev',
    '```',
    '',
    '### Linting',
    'Run static analysis across all workspaces using your shared ESLint rules:',
    '```bash',
    'pnpm lint',
    '```',
    '',
    '### Formatting',
    'Automatically format all codebase files using Prettier:',
    '```bash',
    'pnpm format',
    '```',
    '',
    '---',
    '',
    '*Generated with love by [Morax Scaffolder CLI](https://github.com/Elitedv/morax).*',
    '',
  ].join('\n');

  await fsPromises.writeFile(readmePath, readmeContent, 'utf8');
}
