import fsPromises from 'fs/promises';
import path from 'path';

export async function generateWorkspaceConfig(
  name: string,
  directories: ('apps' | 'packages')[],
  projectPath: string,
) {
  // 1. Create target folder if it doesn't exist
  await fsPromises.mkdir(projectPath, { recursive: true });

  // 2. Generate pnpm-workspace.yaml based on user's selective input
  const workspaceYamlContent = [
    'packages:',
    ...directories.map((dir) => `  - '${dir}/*'`),
    '',
  ].join('\n');

  await fsPromises.writeFile(
    path.join(projectPath, 'pnpm-workspace.yaml'),
    workspaceYamlContent,
    'utf8',
  );

  // 3. Generate Root package.json
  const packageJson = {
    name,
    version: '1.0.0',
    description: 'High-performance monorepo workspace generated by Morax',
    private: true,
    packageManager: 'pnpm@9.15.4',
    workspaces: directories.map((dir) => `${dir}/*`),
    scripts: {
      dev: 'pnpm --filter morax-web dev',
    },
  };

  await fsPromises.writeFile(
    path.join(projectPath, 'package.json'),
    JSON.stringify(packageJson, null, 2),
    'utf8',
  );
}
