import fsPromises from 'fs/promises';
import path from 'path';
import { runCommand } from '../utils/exec.js';

export async function generateWorkspaceConfig(
  name: string,
  directories: ('apps' | 'packages')[],
  projectPath: string,
) {
  // 1. Create target folder if it doesn't exist
  await fsPromises.mkdir(projectPath, { recursive: true });

  // 2. Generate pnpm-workspace.yaml based on user's selective input
  const workspaceYamlContent = [
    'packages:',
    ...directories.map((dir) => `  - '${dir}/*'`),
    '',
  ].join('\n');

  await fsPromises.writeFile(
    path.join(projectPath, 'pnpm-workspace.yaml'),
    workspaceYamlContent,
    'utf8',
  );

  // 3. Generate Root package.json using pnpm init
  await runCommand('pnpm init', { cwd: projectPath, silent: true });

  // 4. Read, parse and customize the package.json
  const packageJsonPath = path.join(projectPath, 'package.json');
  const packageJsonRaw = await fsPromises.readFile(packageJsonPath, 'utf8');
  const pkg = JSON.parse(packageJsonRaw);

  pkg.name = name;
  pkg.description = 'High-performance monorepo workspace generated by Morax';
  pkg.private = true;
  pkg.packageManager = 'pnpm@9.15.4';
  pkg.workspaces = directories.map((dir) => `${dir}/*`);
  pkg.scripts = {
    dev: 'pnpm --filter morax-web dev',
  };

  // Remove entry points since workspace root is private and has no main entry
  delete pkg.main;

  await fsPromises.writeFile(
    packageJsonPath,
    JSON.stringify(pkg, null, 2),
    'utf8',
  );
}
